### ISSUE TITLE
Sistema nao esta removendo do ArrayList pessoas com caracteristicas que deveriam ser removidas

### ISSUE THREAD

**Issue by ProjectIntII** [ProjectIntII/projeto_integrador_2#1]
Passos para reproduzir bug:
1 - Sete a pessoa 1 e a pessoa 2 como "calvo=true".
2 - Responda a pergunta "A pessoa que você esta pensando é calva?" como false.
3 - O sistema remove a pessoa 1 do ArrayList, mas a pessoa 2 nao é removida, sendo que, a caracterista de calvo esta como "true", logo, deveria ser removida.

**Comment by mtsuzena** [comment]
Problema solucionado!
